// components/play/GameView.tsx
import { useSnapshot } from "valtio";
import { Engine } from "@/engine";
import { UIStore } from "@/store/ui.store";
import style from "@/styles/Play.module.scss";

type TProps = {
    engine: React.RefObject<Engine>;
    canvas: React.RefObject<{
        background: {},
        techos: {},
        foreground: {},
        items: {},
        textos: {},
    }>;
}

const GameView = ({ engine, canvas }: TProps) => {
    const uiStore = useSnapshot(UIStore);

    const handleClickCanvas = (e) => {
        let xCanvas = e.nativeEvent.offsetX;
        let yCanvas = e.nativeEvent.offsetY;
        const user = engine.current.user;

        const posX = Math.round(user.pos.x + xCanvas / 32 - 544 / 64);
        const posY = Math.round(user.pos.y + yCanvas / 32 - 544 / 64);

        engine.current.clickCanvas({
            x: posX,
            y: posY,
        });
    };

    return <>
        <canvas
            width="544"
            height="544"
            id="background"
            className={style.background}
            ref={(ref) => {
                canvas.current.background = ref;
            }}
        />
        <canvas
            width="544"
            height="544"
            id="foreground"
            className={style.foreground}
            ref={(ref) => {
                canvas.current.foreground = ref;
            }}
        />
        <canvas
            width="544"
            height="544"
            id="items"
            className={style.items}
            ref={(ref) => {
                canvas.current.items = ref;
            }}
        />
        <canvas
            width="544"
            height="544"
            id="techos"
            className={style.techos}
            ref={(ref) => {
                canvas.current.techos = ref;
            }}
        />
        <canvas
            width="544"
            height="544"
            id="textos"
            className={style.textos}
            ref={(ref) => {
                canvas.current.textos = ref;
            }}
        />
        <canvas
            width="544"
            height="544"
            id="mouseEvent"
            className={style.mouseEvent}
            onClick={handleClickCanvas}
            style={{
                cursor: uiStore.crosshair ? "crosshair" : "default",
            }}
        />
    </>;
};

export default GameView;

// app/components/play/GameView.vue
<script setup lang="ts">
import { useUIStore } from "@/store/ui.store";
import type { Engine } from "@/engine";

const { engine } = defineProps<{
  engine: Engine;
  // canvas: {
  //   background: {};
  //   techos: {};
  //   foreground: {};
  //   items: {};
  //   textos: {};
  // };
}>();
defineEmits<{}>();

const uiStore = useUIStore();
const canvasBackground = ref<HTMLCanvasElement>();
const canvasForeground = ref<HTMLCanvasElement>();
const canvasItems = ref<HTMLCanvasElement>();
const canvasTechos = ref<HTMLCanvasElement>();
const canvasTextos = ref<HTMLCanvasElement>();

const handleClickCanvas = (e: MouseEvent) => {
  let xCanvas = e.offsetX;
  let yCanvas = e.offsetY;
  const user = engine.user;

  const posX = Math.round(user.pos.x + xCanvas / 32 - 544 / 64);
  const posY = Math.round(user.pos.y + yCanvas / 32 - 544 / 64);

  engine.clickCanvas({
    x: posX,
    y: posY,
  });
};

defineExpose({
  canvasBackground,
  canvasForeground,
  canvasItems,
  canvasTechos,
  canvasTextos,
});
</script>

<template>
  <template>
    <canvas width="544" height="544" id="canvas_background" class="background" />
    <canvas width="544" height="544" id="canvas_foreground" class="foreground" />
    <canvas width="544" height="544" id="canvas_items" class="items" />
    <canvas width="544" height="544" id="canvas_techos" class="techos" />
    <canvas width="544" height="544" id="canvas_textos" class="textos" />
    <canvas
      width="544"
      height="544"
      id="canvas_mouseEvent"
      class="mouseEvent"
      @click="handleClickCanvas"
      :style="{
        cursor: uiStore.ui.crosshair ? 'crosshair' : 'default',
      }"
    />
  </template>
</template>

<style scoped>
.background {
  z-index: 0;
  position: absolute;
}
.foreground {
  z-index: 2;
  position: absolute;
}
.items {
  z-index: 1;
  position: absolute;
}
.characters {
  z-index: 3;
  position: absolute;
}
.techos {
  z-index: 4;
  position: absolute;
}
.textos {
  z-index: 5;
  position: absolute;
}
.mouseEvent {
  z-index: 7;
  position: absolute;
}
</style>
